language: python

sudo: false

python:
  - 2.7
  - 3.4
  - 3.5
  - 3.6

addons:
  artifacts:
    s3_region: $ARTIFACTS_REGION
    paths:
      - $(ls $TRAVIS_BUILD_DIR/dist/*.whl | tr "\n" ":")

install:
  - pip install tox-travis
  - python -m pip install -r requirements.build
  - python -m pip install -r requirements.test

script:
  - python setup.py bdist_wheel
  - tox
  - codecov

deploy:
  provider: pypi
  user: altendky
  password: $PYPI_PASSWORD
  on:
    branch: develop
    tags: true
    condition: $TRAVIS_PYTHON_VERSION = 3.6
  distributions: bdist_wheel
