environment:
  VENV: "%APPVEYOR_BUILD_FOLDER%\\..\\venv"
  VENV_BIN: "%VENV%\\Scripts"
  VENV_PYTHON: "%VENV_BIN%\\python"

  matrix:
    - TOXENV: py36
      PYTHON: "C:\\Python36-x64"

init:
  - echo "TOXENV- %TOXENV%"

install:
  - "%PYTHON%\\Scripts\\pip install --user virtualenv"
  - "%PYTHON%\\Scripts\\virtualenv -p \"%PYTHON%\\python.exe\" \"%VENV%\""
  - "%VENV_PYTHON% -m pip install -r requirements.build"
  - "%VENV_PYTHON% -m pip install -r requirements.test"

build_script:
  - "%VENV_PYTHON% setup.py bdist_wheel"

test_script:
  - "%VENV_PYTHON% -m tox"

artifacts:
  - path: "dist\\*.whl"
