matrix:
  global:
    - VENV: "%APPVEYOR_BUILD_FOLDER%\\..\\venv"
    - VENV_BIN: "%VENV%\\Scripts"
    - VENV_PYTHON: "%VENV_BIN%\\python"
  - TOXENV: py36
    PYTHON: "C:\\Python36-x64"

init:
  - echo "TOXENV: %TOXENV%"

install:
  - "%PYTHON%\\Scripts\\pip" install --user virtualenv
  - "%PYTHON%\\Scripts\\virtualenv" -p "%PYTHON%\\Scripts\\python" "%VENV%"
  - "%VENV_PYTHON%" -m pip install tox

test_script:
  - "%VENV_BIN%" -m tox
