environment:
  VENV: "%APPVEYOR_BUILD_FOLDER%\\venv"

  matrix:
    - TOXENV: py27
      PYTHON: "C:\\Python27-x64"

    - TOXENV: py34
      PYTHON: "C:\\Python34-x64"

    - TOXENV: py35
      PYTHON: "C:\\Python35-x64"

    - TOXENV: py36
      PYTHON: "C:\\Python36-x64"
      BUILD_WHEEL: 1

init:
  - echo "TOXENV- %TOXENV%"

install:
  - virtualenv -p "%PYTHON%\\python.exe" "%VENV%"
  - "%VENV%\\Scripts\\activate"
  - pip install .
  - ps: Update-AppveyorBuild -Version "v$(C:\\Python36-x64\\python -c 'import graham; print(graham.__version__, end=\"\")') b$Env:APPVEYOR_BUILD_NUMBER"
  - pip install -r requirements.build
  - pip install -r requirements.test

build_script:
  - if defined BUILD_WHEEL python setup.py bdist_wheel --universal

test_script:
  - tox
  - codecov

artifacts:
  - path: "dist\\*.whl"
