environment:
  VENV: "%APPVEYOR_BUILD_FOLDER%\\venv"

  matrix:
    - TOXENV: py27
      PYTHON: "C:\\Python27-x64"

    - TOXENV: py34
      PYTHON: "C:\\Python34-x64"

    - TOXENV: py35
      PYTHON: "C:\\Python35-x64"

    - TOXENV: py36
      PYTHON: "C:\\Python36-x64"
      BUILD_WHEEL: 1

init:
  - echo "TOXENV- %TOXENV%"

install:
  - py boots.py create --group package
  - ps: Update-AppveyorBuild -Version "v$(python -c 'import sys; import graham; sys.stdout.write(graham.__version__)') b$Env:APPVEYOR_BUILD_NUMBER"

build_script:
  - if defined BUILD_WHEEL python boots.py build

test_script:
  - tox
  - codecov

artifacts:
  - path: "dist\\*.whl"
