environment:
  VENV: "%APPVEYOR_BUILD_FOLDER%\\venv"

  matrix:
    - TOXENV: py36
      PYTHON: "C:\\Python36-x64"

init:
  - echo "TOXENV- %TOXENV%"

install:
  - virtualenv -p "%PYTHON%\\python.exe" "%VENV%"
  - "%VENV%\\Scripts\\activate"
  - pip install .
  - ps: Update-AppveyorBuild -Version "v$(python -c 'import graham; print(graham.__version__, end=\"\")') b$Env:APPVEYOR_BUILD_NUMBER"
  - pip install -r requirements.build
  - pip install -r requirements.test

build_script:
  - python setup.py bdist_wheel

test_script:
  - tox
  - codecov

artifacts:
  - path: "dist\\*.whl"
